CI_task:
  only_if: $CIRRUS_BRANCH == 'main' || $CIRRUS_BASE_BRANCH == 'main' || $CIRRUS_TAG != ''
  auto_cancellation: true
  env:
    JOBS: '2'
    TIMEOUT: '600'
    EXTRA_ARGS: ''
  container:
    dockerfile: .github/Dockerfile
    cpu: 1
    memory: 4G
    greedy: true
  notebook_script: >
    find docs/ -name '*.ipynb' |
    parallel -j${JOBS} --joblog /tmp/log
    jupyter nbconvert --to notebook
    --ExecutePreprocessor.timeout=${TIMEOUT}
    --ExecutePreprocessor.kernel_name=$(julia -e 'print("julia-1.",VERSION.minor)')
    --execute --inplace ${EXTRA_ARGS}
  stats_script: cat /tmp/log
  notebooks_artifacts:
    path: "docs/**"
